---
# handlers for ansible-role-homebrew

- name: "Homebrew | Clear homebrew cache"
  ansible.builtin.file:
    path: "{{ homebrew_cache_path.stdout | trim }}"
    state: absent
  when: 'homebrew_clear_cache | bool'
  become: "{{ (user_info.user_name != ansible_user_id) | bool }}"
  become_user: "{{ user_info.user_name }}"